version: "3.7"
services:
  node-installer:
    image: node:20.11.1
    volumes:
      - ./:/home/node/project
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    user: 1000:1000
    command: npm i

  duplo:
    image: node:20.11.1
    volumes:
      - ./:/home/node/project
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    user: 1000:1000
    command: npm -w duplo run start
    ports:
      - 5678:5555
    depends_on:
      node-installer:
        condition: service_completed_successfully

  vue-builder:
    image: node:20.11.1
    volumes:
      - ./:/home/node/project
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    user: 1000:1000
    command: npm -w vue run build-only
    depends_on:
      node-installer:
        condition: service_completed_successfully

  nginx:
    image: nginx
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./vue/dist:/home/nginx/dist
    ports:
      - 5956:80
    depends_on:
      vue-builder:
        condition: service_completed_successfully
      duplo:
        condition: service_started
    attach: false

  minio:
    image: minio/minio:latest
    ports:
      - 8900:8900
    env_file: ./duplo/.env
    volumes:
      - "minio_data:/data/minio"
    command: server /data/minio --console-address ":8900"

  postgres:
    image: postgres:16.2
    env_file: ./duplo/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    attach: false

  mongo:
    image: mongo
    env_file: ./duplo/.env
    volumes:
      - "mongo_data:/data/db"
    attach: false

  stripe-installer:
    image: stripe/stripe-cli
    env_file: ./duplo/.env.local
    volumes:
      - ./stripe:/home
    entrypoint: /bin/sh
    command: /home/cp.sh

  cron: 
    image: node:20.11.1
    environment:
      npm_config_cache: /home/node/cache
    user: 1000:1000
    env_file: ./duplo/.env
    working_dir: /home/node/project
    volumes:
      - ./:/home/node/project
    command: npm run cron
    depends_on:
      node-installer:
        condition: service_completed_successfully
    
  mongo-viewer:
    image: mongo-express
    ports:
      - 8081:8081
    env_file: ./duplo/.env
    
volumes:
  postgres_data:
  mongo_data:
  minio_data:
